# Generated by Django 4.2.18 on 2025-01-18 13:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_category_created_at_category_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Discounted price of the product.",
                max_digits=10,
                null=True,
                validators=[
                    products.models.validate_positive_decimal,
                    django.core.validators.MinValueValidator(Decimal("10.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Original price of the product.",
                max_digits=10,
                validators=[
                    products.models.validate_positive_decimal,
                    django.core.validators.MinValueValidator(Decimal("10.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(
                help_text="Stock quantity.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
    ]
