# Generated by Django 4.2.17 on 2024-12-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0002_vendor_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="phone_number",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
