# Generated by Django 4.2.17 on 2024-12-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("CUS", "Customer"),
                    ("VEN", "Vendor"),
                    ("ADMIN", "Administrator"),
                ],
                default="CUS",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="default_user.jpg", null=True, upload_to="profiles/"
            ),
        ),
    ]
